name: lse-atq

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-lse-atq
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ../app:/var/www/html
      - writable_data:/var/www/html/writable
      - vendor_data:/var/www/html/vendor
    command: >
      bash -lc "mkdir -p /var/www/html/writable/cache/blade
      /var/www/html/writable/service_log
      /var/www/html/public/assets/captcha_images
      && chown -R www-data:www-data /var/www/html/writable
      && chmod -R 775 /var/www/html/writable
      && chmod -R 777 /var/www/html/public/assets/captcha_images
      && php-fpm -F"
    networks:
      - localnet

  nginx:
    image: nginx:alpine
    container_name: nginx-lse-atq
    ports:
      - "8087:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - localnet

networks:
  localnet:
    external: true

volumes:
  writable_data:
  vendor_data: