name: db-lse-atq
services:
  db:
    image: mysql:8.0
    container_name: db-lse-atq
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lse_atq_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
    ports:
      - "33061:3306"
    volumes:
      - ../database/:/docker-entrypoint-initdb.d
      - ../database/ddbprod:/var/lib/mysql
      # - ../database/disable_strict_mode.cnf:/etc/mysql/conf.d/disable_strict_mode.cnf
      # - ../database/my.cnf:/etc/my.cnf
    networks:
      - localnet
networks:
  localnet:
    external: true